/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicio2;

import java.util.Scanner;

public class App {
    
    public static void main(String[] args) {
        Game game = new Game();
        game.start();
    }
}
