/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicio1;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Scanner scan = new Scanner(System.in);
        Calculadora calc = new Calculadora();
        double n1, n2;
        
        System.out.println("Digite um numero:");
        n1 = scan.nextDouble();
        System.out.println("Digite outro numero:");
        n2 = scan.nextDouble();        
        
        System.out.println("O resultado da soma e: " + calc.soma(n1, n2));
        System.out.println("O resultado da subtracao e: " + calc.subtracao(n1, n2));
        System.out.println("O resultado da multiplicacao e: " + calc.multiplicacao(n1, n2));
        System.out.println("O resultado da divisao e: " + (calc.divisao(n1, n2)));
        
        
        scan.close();
        
        
        
    }
}
