/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package meuSegundoProjetoJava;
import java.util.ArrayList;
import java.util.Scanner;

public class App {
       
//    private static boolean retornaMusica(String leter) {
//        String myLeter = "Naquela mesa ele contava historias que hoje na memoria eu guardo e sei de cor";
//        
//        boolean isEqual = myLeter.toLowerCase().equals(leter.toLowerCase());
//        return isEqual;
//    }
   
    
    public static void main(String[] args) {
//        String leter;
//        Scanner scan = new Scanner(System.in);
//
//        System.out.println("Naquela mesa ele sentava sempre e me dizia sempre o que é viver melhor!");     
//        System.out.println("Continue a musica: ");
//        leter = scan.nextLine();
//        
//                     
//        System.out.println(leter);
//        
//        if(App.retornaMusica(leter)) {
//            System.out.println(("PARABENS, VOCE sabe MPB BASICO").toUpperCase());
//        } else {
//            System.out.println("INUTIL, NAO SABE MPB BASICO");
//        }

        int[] b;
        b = new int[10];
        for(int i = 0; i < b.length; i++) {
          b[i] = 3*i;
          System.out.println(b[i]);
        }
          
        System.out.println(b.length);
        
//      Cria um objeto Scanner para ler a entrada do usuário
        Scanner sc = new Scanner(System.in);
        
//      Declara duas variáveis inteiras para armazenar os números digitados pelo usuário
        int numero1, numero2;
        
        String nome; 

        
//      Solicita ao usuário que digite o primeiro número
        System.out.println("Digite um número: ");
        numero1 = sc.nextInt(); // Lê o próximo inteiro digitado pelo usuário e o armazena em numero1

        sc.nextLine();
        System.out.println("Digite seu nome:"); 
        nome = sc.nextLine();        
        
//      Solicita ao usuário que digite o segundo número
        System.out.println("Digite outro número: ");
        numero2 = sc.nextInt(); // Lê o próximo inteiro digitado pelo usuário e o armazena em numero2

//      Exibe uma mensagem para indicar que o resultado será mostrado
        System.out.println(nome + ", o resultado: " + (numero1 + numero2));

        sc.close();
        
    }
}
