/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package meuProjetoJava;
import java.util.Scanner;

public class App {
    
    public void promocao(Produto meuProd) {
        System.out.println("O produto " + meuProd.getName() + " está em promoção por apenas " + meuProd.getPreco()); 
    }
    
    public static void main(String[] args) {
    
    Scanner sc = new Scanner(System.in);
    
    int numero1, numero2;
    
    System.out.println("Digite um numero: ");
    numero1 = sc.nextInt();
    
    System.out.println("Digite outro numero: ");
    numero2 = sc.nextInt();
        
    System.out.println("Resultado: " + (numero1 * numero2));
    sc.close();
        /*
    int age = 21;
    String name = "Vitor Reis";
    double height = 1.70;
    char initial = 'V';
    boolean souEstudante = true;
    age = 22;
    int numero = 12;
        
            
    if(numero > 10) {
        System.out.println("O número é maior que 10");
    } else if (numero == 10) {
        System.out.println("O número é igual a 10");
    } else {
        System.out.println("O número é menor que 10");
    }       
            
    System.out.println("Meu nome e " + name + " e minha altura e " + height + ", minha inicial e " + initial + " e minha idade e " + age);
    

    
    int weekDay = 5;
    
    switch(weekDay) {
        case 1: 
        System.out.println("Domingo");
        break;
        case 2:
        System.out.println("Segunda-Feira");
        break;
        case 3:
        System.out.println("Terça-Feira");
        break;
        case 4:
        System.out.println("Quarta-Feira");
        break;
        case 5:
        System.out.println("Quinta-Feira");
        break;
        case 6:
        System.out.println("Sexta-Feira");
        break;
        case 7:
        System.out.println("Sábado");
        break;
        default:
            System.out.println("Isso não é um dia da semana");
        break;
    }
    
    
    
    
    int impar = 22;
    
    if(impar % 2 == 1) {
        System.out.println("impar");
    } else {
        System.out.println("par");
    }
    
    String resultado = (impar % 2 == 0) ? "Par" : "Impar";
    System.out.println(resultado);

    int voltas = 0;
    
//    while(voltas <= 100) {
//        System.out.println(voltas);
//        voltas++;
//    }
    
    for (int i = 0; i <= 10; i++) {
        System.out.println(i + " easy gg d+ pica");
    }
    
    
    int numero1 = 10;
    int numero2 = 50;
    
    Calculadora teste = new Calculadora();
    teste.somar(numero1, numero2);
    
    
    Pessoa novaPessoa = new Pessoa("Vitor", 22);
    novaPessoa.caminhar();
    System.out.println(novaPessoa.nome);
    
    Produto novoProduto = new Produto("Café Melitta", 32);
    novoProduto.getName();
    System.out.println(novoProduto.getName());
    
    Eletronico novoElet = new Eletronico("TV", 1500, 220);
    novoElet.getTensao();
    novoElet.getName();
    
    System.out.println(novoElet.getTensao());
    System.out.println(novoElet.getName());
    
    App meuApp = new App();
    meuApp.promocao(novoElet);
    */
    
    
        
//    Calculadora.somar(numero1, numero2);
    } // Final da main
       
}
